#!/usr/bin/env bash

set -eEuo pipefail

if [[ ${#} -lt 1 || -z ${1} ]]; then
	echo >&2 'FATAL: problem ID string not supplied'
	exit 1
fi

PROB_ID="${1}"
mkdir "${PROB_ID}"

cat >"${PROB_ID}/README.md" <<EOF
# [$PROB_ID](https://leetcode.com/problems/$PROB_ID/)
EOF

read -r -n1 -s -p 'Copy solution to clipboard, then press any key here...'
pbpaste >"${PROB_ID}/${PROB_ID}.py"

git add "${PROB_ID}/"
git commit -m "add ${PROB_ID} py"

git pull --rebase
git push
