#!/usr/bin/env bash

set -eEuo pipefail

if [[ "${#}" -lt 1 || -z "${1}" ]]; then
	>&2 echo 'problem ID string not supplied'
	exit 1
fi

PROB_ID="${1}"

mkdir "${PROB_ID}"

>"${PROB_ID}/README.md" cat <<EOF
# [$PROB_ID](https://leetcode.com/problems/$PROB_ID/)
EOF

vi "${PROB_ID}/${PROB_ID}.py"

git add "${PROB_ID}/"
git commit

git pull --rebase
git push
